In [1]:
import numpy as np
import pandas as pd
import random
from sklearn.svm import SVC

# Diagnosis

## All data 

In [2]:
df = pd.read_csv(r'C:\Users\caron\OneDrive - University of North Carolina at Chapel Hill\Honors Project\CSV Files\MRI Data.csv')
temp = pd.concat([df.loc[0:, ['SDx']], df.loc[0:, 'L_LatVent': 'R_insula_surfavg']], axis=1, sort=False)
temp = temp.dropna(how='any')
df1 = temp.loc[0:, ['SDx']]
df2 = temp.loc[0:, 'L_LatVent': 'R_insula_surfavg']
df

Site  SubjID  Dx  SDx  Age  Sex  Handedness    AO  DURILL  L_LatVent  \
0        1      39   0    0   26    2         NaN   NaN     NaN     3655.0   
1        1      56   0    0   30    2         NaN   NaN     NaN     4885.0   
2        1      67   0    0   25    2         NaN   NaN     NaN     6065.0   
3        1     132   0    0   50    2         NaN   NaN     NaN     6941.0   
4        1     136   0    0   29    1         NaN   NaN     NaN     7553.0   
...    ...     ...  ..  ...  ...  ...         ...   ...     ...        ...   
1906    16      44   1    3   41    1         1.0  41.0     0.0     8780.8   
1907    16       5   1    3   27    1         1.0  26.0     1.0     3161.4   
1908    16      53   1    3   46    2         1.0  29.0    17.0     3519.5   
1909    16      59   1    3   25    1         1.0   5.0    20.0     4635.8   
1910    16       7   1    3   20    2         1.0   NaN     NaN     4363.2   

      ...  R_rostralanteriorcingulate_surfavg  R_rostralmiddlefrontal_surfavg  \
0     ...                               714.0                          5887.0   
1     ...                               708.0                          4955.0   
2     ...                               882.0                          5703.0   
3     ...                               647.0                          5782.0   
4     ...                               802.0                          5965.0   
...   ...                                 ...                             ...   
1906  ...                              1053.0                          6365.0   
1907  ...                               726.0                          5236.0   
1908  ...                               661.0                          5959.0   
1909  ...                               676.0                          4632.0   
1910  ...                               796.0                          6488.0   

      R_superiorfrontal_surfavg  R_superiorparietal_surfavg  \
0                        7100.0                      5952.0   
1                        6524.0                      4878.0   
2                        7052.0                      5066.0   
3                        7226.0                      4691.0   
4                        8310.0                      5416.0   
...                         ...                         ...   
1906                     7041.0                      5813.0   
1907                     6705.0                      5839.0   
1908                     7597.0                      5603.0   
1909                     5960.0                      4005.0   
1910                     7769.0                      5821.0   

      R_superiortemporal_surfavg  R_supramarginal_surfavg  \
0                         3312.0                   3372.0   
1                         3875.0                   3943.0   
2                         3386.0                   4190.0   
3                         3478.0                   3986.0   
4                         4498.0                   4455.0   
...                          ...                      ...   
1906                      3648.0                   3681.0   
1907                      3528.0                   3674.0   
1908                      3539.0                   3981.0   
1909                      2792.0                   2998.0   
1910                      4121.0                   4709.0   

      R_frontalpole_surfavg  R_temporalpole_surfavg  \
0                     236.0                   383.0   
1                     268.0                   409.0   
2                     189.0                   606.0   
3                     240.0                   468.0   
4                     284.0                   479.0   
...                     ...                     ...   
1906                  247.0                   585.0   
1907                  225.0                   413.0   
1908                  184.0                   547.0   
1909                  201.0                   394.0   
1

In [3]:
y = np.array(df1).ravel()
x = np.array(df2)

In [4]:
model = SVC(kernel='rbf', random_state=0, gamma=100000, C=100000)
model.fit(x, y)

SVC(C=100000, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=100000, kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [5]:
model.score(x, y)

0.9980861244019139

## Split

In [6]:
temp = pd.concat([df.loc[0:, ['SDx']], df.loc[0:, 'L_LatVent': 'R_insula_surfavg']], axis=1, sort=False).dropna(how='any').sample(frac=1).reset_index(drop=True)  
train = temp[:523]
test = temp[523:]
df1_train = train.loc[0:, ['SDx']]
df2_train = train.loc[0:, 'L_LatVent': 'R_insula_surfavg']
df1_test = test.loc[0:, ['SDx']]
df2_test = test.loc[0:, 'L_LatVent': 'R_insula_surfavg']

In [7]:
y_train = np.array(df1_train).ravel()
x_train = np.array(df2_train)
y_test = np.array(df1_test).ravel()
x_test = np.array(df2_test)

In [8]:
model = SVC(gamma='auto')
model.fit(x_train, y_train)
model.score(x_train, y_train)

1.0

In [9]:
model.score(x_test, y_test)

0.6762452107279694

In [10]:
df2_test_array = np.array(df2_test)
df2_test_array

array([[ 3194.7,  2813.3,  7478.8, ...,   400. ,   311. ,  2198. ],
       [ 4779.4,  6062.9,  8185.2, ...,   390. ,   368. ,  2164. ],
       [ 4964.2,  3857. ,  7890.2, ...,   447. ,   315. ,  1932. ],
       ...,
       [ 4885. ,  5397. ,  7249. , ...,   543. ,   332. ,  2213. ],
       [ 3457.8,  3194.2,  7567.9, ...,   414. ,   306. ,  2243. ],
       [11745.5,  8042.1,  8219.8, ...,   263. ,   322. ,  1725. ]])

In [11]:
for it in df2_test_array:
    print(model.predict([it]))

[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[3]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[3]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]


# Sex

## All Data

In [12]:
temp = pd.concat([df.loc[0:, ['Sex']], df.loc[0:, 'L_LatVent': 'R_insula_surfavg']], axis=1, sort=False)
temp = temp.dropna(how='any')
df1 = temp.loc[0:, ['Sex']]
df2 = temp.loc[0:, 'L_LatVent': 'R_insula_surfavg']

In [13]:
y = np.array(df1).ravel()
x = np.array(df2)

In [14]:
model = SVC(kernel='rbf', random_state=0, gamma=100, C=100)
model.fit(x, y)

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=100, kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [15]:
model.score(x, y)

0.9942583732057416

## Split

In [16]:
temp = pd.concat([df.loc[0:, ['Sex']], df.loc[0:, 'L_LatVent': 'R_insula_surfavg']], axis=1, sort=False).dropna(how='any').sample(frac=1).reset_index(drop=True)  
train = temp[:523]
test = temp[523:]
df1_train = train.loc[0:, ['Sex']]
df2_train = train.loc[0:, 'L_LatVent': 'R_insula_surfavg']
df1_test = test.loc[0:, ['Sex']]
df2_test = test.loc[0:, 'L_LatVent': 'R_insula_surfavg']

In [17]:
y_train = np.array(df1_train).ravel()
x_train = np.array(df2_train)
y_test = np.array(df1_test).ravel()
x_test = np.array(df2_test)

In [18]:
model = SVC(kernel='rbf', random_state=0, gamma=100, C=100)
model.fit(x_train, y_train)
model.score(x_train, y_train)

0.9961759082217974

In [19]:
model.score(x_test, y_test)

0.5459770114942529

In [20]:
df2_test_array = np.array(df2)
df2_test_array

array([[3655. , 4525. , 7829. , ...,  383. ,  327. , 2090. ],
       [4885. , 3312. , 7567. , ...,  409. ,  272. , 2215. ],
       [6065. , 6765. , 7823. , ...,  606. ,  266. , 2466. ],
       ...,
       [3519.5, 4556.5, 6929.9, ...,  547. ,  496. , 2397. ],
       [4635.8, 6822.7, 6094. , ...,  394. ,  361. , 1915. ],
       [4363.2, 3547.3, 6977.2, ...,  455. ,  517. , 2425. ]])

In [21]:
for it in df2_test_array:
    print(model.predict([it]))

[2]
[2]
[2]
[2]
[2]
[1]
[2]
[2]
[2]
[2]
[1]
[2]
[2]
[2]
[2]
[1]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[1]
[1]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[1]
[1]
[1]
[2]
[2]
[2]
[2]
[1]
[2]
[2]
[2]
[1]
[2]
[1]
[1]
[2]
[2]
[2]
[2]
[1]
[1]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[1]
[2]
[2]
[2]
[2]
[2]
[1]
[2]
[2]
[2]
[2]
[1]
[2]
[1]
[2]
[1]
[1]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[1]
[2]
[2]
[1]
[2]
[1]
[2]
[1]
[2]
[2]
[2]
[2]
[1]
[2]
[2]
[2]
[2]
[2]
[2]
[1]
[1]
[2]
[2]
[2]
[2]
[2]
[1]
[2]
[1]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[1]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[1]
[2]
[2]
[2]
[2]
[2]
[1]
[1]
[2]
[1]
[2]
[2]
[1]
[2]
[1]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[1]
[1]
[2]
[1]
[2]
[1]
[2]
[2]
[1]
[2]
[2]
[2]
[2]
[2]
[1]
[1]
[2]
[2]
[2]
[1]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[1]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[1]
[2]
[2]
[2]
[1]
[2]
[1]
[2]
[1]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[1]
[2]
[2]
[2]
[2]
[2]
[2]
[1]
[1]
[2]
[2]
[2]
[2]


# Site

## All Data

In [22]:
temp = pd.concat([df.loc[0:, ['Site']], df.loc[0:, 'L_LatVent': 'R_insula_surfavg']], axis=1, sort=False)
temp = temp.dropna(how='any')
df1 = temp.loc[0:, ['Site']]
df2 = temp.loc[0:, 'L_LatVent': 'R_insula_surfavg']

In [23]:
y = np.array(df1).ravel()
x = np.array(df2)

In [24]:
model = SVC(kernel='rbf', random_state=0, gamma=100, C=100)
model.fit(x, y)

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=100, kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [25]:
model.score(x, y)

1.0

## Split Data

In [26]:
temp = pd.concat([df.loc[0:, ['Site']], df.loc[0:, 'L_LatVent': 'R_insula_surfavg']], axis=1, sort=False).dropna(how='any').sample(frac=1).reset_index(drop=True)  
train = temp[:523]
test = temp[523:]
df1_train = train.loc[0:, ['Site']]
df2_train = train.loc[0:, 'L_LatVent': 'R_insula_surfavg']
df1_test = test.loc[0:, ['Site']]
df2_test = test.loc[0:, 'L_LatVent': 'R_insula_surfavg']

In [27]:
y_train = np.array(df1_train).ravel()
x_train = np.array(df2_train)
y_test = np.array(df1_test).ravel()
x_test = np.array(df2_test)

In [28]:
model = SVC(gamma='auto')
model.fit(x_train, y_train)
model.score(x_train, y_train)

1.0

In [29]:
model.score(x_test, y_test)

0.18582375478927204

In [30]:
df2_test_array = np.array(df2)
df2_test_array

array([[3655. , 4525. , 7829. , ...,  383. ,  327. , 2090. ],
       [4885. , 3312. , 7567. , ...,  409. ,  272. , 2215. ],
       [6065. , 6765. , 7823. , ...,  606. ,  266. , 2466. ],
       ...,
       [3519.5, 4556.5, 6929.9, ...,  547. ,  496. , 2397. ],
       [4635.8, 6822.7, 6094. , ...,  394. ,  361. , 1915. ],
       [4363.2, 3547.3, 6977.2, ...,  455. ,  517. , 2425. ]])

In [31]:
for it in df2_test_array:
    print(model.predict([it]))

[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[2]
[1]
[2]
[2]
[1]
[2]
[1]
[2]
[2]
[1]
[2]
[1]
[1]
[2]
[1]
[2]
[1]
[2]
[2]
[2]
[2]
[1]
[1]
[2]
[1]
[2]
[1]
[2]
[1]
[1]
[1]
[2]
[2]
[2]
[2]
[1]
[2]
[1]
[1]
[2]
[2]
[2]
[1]
[1]
[3]
[1]
[3]
[3]
[1]
[3]
[1]
[3]
[3]
[1]
[3]
[1]
[3]
[3]
[1]
[1]
[3]
[1]
[3]
[1]
[1]
[3]
[1]
[1]
[1]
[1]
[3]
[1]
[3]
[3]
[3]
[1]
[1]
[1]
[1]
[3]
[3]
[1]
[4]
[1]
[1]
[4]
[4]
[1]
[4]
[1]
[1]
[1]
[4]
[1]
[4]
[1]
[1]
[1]
[4]
[4]
[4]
[1]
[4]
[1]
[1]
[1]
[1]
[4]
[4]
[1]
[4]
[1]
[4]
[4]
[4]
[1]
[1]
[4]
[1]
[1]
[1]
[4]
[4]
[1]
[4]
[1]
[4]
[4]
[4]
[4]
[1]
[4]
[1]
[1]
[1]
[4]
[1]
[1]
[5]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[5]
[5]
[1]
[1]
[5]
[6]
[1]
[6]
[6]
[1]
[1]
[1]
[6]
[1]
[1]
[1]
[6]
[6]
[1]
[6]
[6]
[6]
[6]
[1]
[1]
[1]
[6]
